### ISSUE TITLE
Unexpected files are include in the npm release 1.0.16

### ISSUE THREAD

**Issue by xdjinnx** [dongariteja/xelement#1]
There are files that are not expected to be included in the npm release of xelement.

These files are: .suo, .npmignore and xelement.sln

You should commit these files to the repository.

OBS! I would not commit the .suo file because this is not an intended file to be commited, see here: https://msdn.microsoft.com/en-us/library/bb165909.aspx

Also I would not commit the .vs folder at all. Because the github gitignore template for VisualStudio suggest to ignore this folder. See: https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

The .suo file is causing problems for everyone using electron-updater at the moment because it's seen as a binary. electron-updater is using xelement as a dependency. The smartUnpack in electron builder is unpacking all dependencies that has a binary or an executable present in the module.

**Comment by develar** [comment]
electron-builder 19.37.1 will exclude such files.

electron-updater 2.12.x will probably use another xml lib.

**Comment by develar** [comment]
https://github.com/electron-userland/electron-builder/releases/tag/v19.37.2

**Comment by xdjinnx** [comment]
Nice fix!

Even though it's fixed in electron-builder. It would be nice for users using an older version of electron-updater to release a new version of xelement fixing mentioned problem.

**Comment by dongariteja** [comment]
all unnecessary files has been removed.
