### ISSUE TITLE
Add NPM 'types' property to package.json

### ISSUE THREAD

**Issue by marlon-tucker** [dongariteja/xelement#2]
Hello,

Please can you add the 'types' property to your package.json file so Typescript types are automatically discovered by IDEs.

Details here : https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

As you already have a definition file you just have to point the property to it. 

`"types": "Typings/xelement.d.ts",`

Thanks

Marlon

**Comment by dongariteja** [comment]
Added types in package.json
